version: "3"

services:
  calcul:
    build: 
      context: ./src
      dockerfile: HotPotatoApi.Dockerfile
    container_name: hotpotato-calcul
    ports:
      - "5176:80"
    environment:
      - MODE=Http
      - ENDPOINT=envoy:10000
      - INSTANCE_NAME=Calcul
    volumes:
      - C:\\logs\\apps:/logs/apps
    networks:
      - hot_potato_network

  rapport:
    build:
      context: ./src
      dockerfile: HotPotatoApi.Dockerfile
    container_name: hotpotato-rapport
    environment:
      - MODE=Http
      - ENDPOINT=envoy:10000
      - INSTANCE_NAME=Rapport
    volumes:
      - C:\\logs\\apps:/logs/apps
    ports:
      - "5177:80"
    networks:
      - hot_potato_network

  portefeuille:
    build:
      context: ./src
      dockerfile: HotPotatoApi.Dockerfile
    container_name: hotpotato-portefeuille
    environment:
      - MODE=Http
      - ENDPOINT=envoy:10000
      - INSTANCE_NAME=Portefeuille
    volumes:
      - C:\\logs\\apps:/logs/apps
    ports:
      - "5178:80"
    networks:
      - hot_potato_network

  pfweb:
    build:
      context: ./src
      dockerfile: HotPotatoApi.Dockerfile
    container_name: hotpotato-pfweb
    environment:
      - MODE=Http
      - ENDPOINT=envoy:10000
      - INSTANCE_NAME=PFWeb
    volumes:
      - C:\\logs\\apps:/logs/apps
    ports:
      - "5179:80"
    networks:
      - hot_potato_network

  envoy:
    image: envoyproxy/envoy:v1.26-latest
    container_name: envoy
    ports:
      - "10000:10000"
      - "9901:9901"
    command: [ "/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml", "--log-level", "debug" ]
    volumes:
      - ./Envoy/envoy-sample.yaml:/etc/envoy/envoy.yaml
    networks:
      - hot_potato_network
        
  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./Grafana/configs/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - hot_potato_network

  tempo:
    image: grafana/tempo:2.0.1
    container_name: tempo
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./Grafana/configs/tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"  # tempo
      - "4317:4317" # grpc traces
    networks:
      - hot_potato_network

  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    volumes:
      - ./Grafana/configs/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command:
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    networks:
      - hot_potato_network

  agent:
    image: grafana/agent:v0.31.0
    container_name: grafana-agent
    volumes:
      - ./Grafana/configs/agent.sample.yaml:/etc/agent-config/agent.yaml
      - C:\\logs\\apps:/var/logs/apps
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
    depends_on:
      - tempo
      - prometheus
      - loki
    networks:
      - hot_potato_network

  grafana:
    image: grafana/grafana:9.2.2
    container_name: grafana
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./Grafana/configs/grafana.ini:/etc/grafana-config/grafana.ini
      - ./Grafana/datasources:/etc/grafana/provisioning/datasources
      - ./Grafana/dashboards/provisioning:/etc/grafana/provisioning/dashboards
      - ./Grafana/dashboards/boards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - hot_potato_network

networks:
  hot_potato_network: