# See Templates/agent.template in HotPotato.CLI project for template used in build

server:
  log_level: info

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      clients:
        - url: 'http://loki:3100/loki/api/v1/push'
      scrape_configs:
        - job_name: apps
          static_configs:
            - targets:
                - localhost
              labels:
                job: apps-logs
                __path__: /var/logs/apps/*.jsonl
          pipeline_stages:
            - json:
                expressions:
                  timestamp: '"@t"'
            - timestamp:
                source: timestamp
                action_on_failure: skip
                format: RFC3339Nano

metrics:
  global:
    scrape_interval: 15s
    remote_write:
      - url: 'http://prometheus:9090/api/v1/write'
  
  configs:
    - name: default
      scrape_configs:
        - job_name: apps
          static_configs:
            - targets: [ 'host.docker.internal:5176', 'host.docker.internal:5177', 'host.docker.internal:5178', 'host.docker.internal:5179' ]
        
#traces:
#  configs:
#    - name: default
#      receivers:
#        otlp:
#          protocols:
#            grpc:
#      remote_write:
#        - endpoint: 'tempo:4317'
#          insecure: true
#      batch:
#        timeout: 5s
#        send_batch_size: 100
        
integrations:
  agent:
    enabled: false
  node_exporter:
    enabled: false