apiVersion: 1

deleteDatasources:
  - name: Tempo
    orgId: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
  jsonData:
    tracesToLogs:
      datasourceUid: 'loki'
    serviceMap:
      datasourceUid: 'prometheus'
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: 'loki'